"use client";

import { useState, useTransition } from "react";
import { Pencil, Plus, Trash2, UserMinus, UserPlus, Users, X } from "lucide-react";
import { deleteClass, saveClass, setClassMember } from "@/app/admin/kelas/actions";
import type { ClassRow, Option } from "@/app/admin/kelas/page-data";

type Props = { rows: ClassRow[]; subjects: Option[]; packages: Option[]; students: { id: string; full_name: string }[]; mentors: { id: string; full_name: string }[] };
type Editing = ClassRow | null | undefined;

export function ClassManager({ rows, subjects, packages, students, mentors }: Props) {
  const [editing, setEditing] = useState<Editing>(); const [message, setMessage] = useState<string>(); const [isPending, startTransition] = useTransition();
  const close = () => { setEditing(undefined); setMessage(undefined); };
  const submit = (form: HTMLFormElement) => startTransition(async () => { const result = await saveClass(editing?.id ?? null, Object.fromEntries(new FormData(form))); if (result.error) setMessage(result.error); else close(); });
  const mutateMember = (kind: "student" | "mentor", classId: string, personId: string, add: boolean) => startTransition(async () => { const result = await setClassMember(kind, classId, personId, add); if (result.error) setMessage(result.error); });
  const remove = (id: string) => { if (!window.confirm("Hapus kelas ini beserta penempatan dan jadwalnya?")) return; startTransition(async () => { const result = await deleteClass(id); if (result.error) setMessage(result.error); }); };
  const selectedStudentIds = new Set(editing?.student_ids ?? []); const selectedMentorIds = new Set(editing?.mentor_ids ?? []);
  return <>
    <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="app-title-primary">Manajemen Kelas</h1><p className="mt-1 text-sm text-slate-500">Atur kelas, siswa, dan mentor pengajar.</p></div><button onClick={() => setEditing(null)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand px-4 py-2.5 text-sm font-semibold text-white hover:bg-brandHover"><Plus size={17}/>Tambah Kelas</button></div>
    <div className="grid gap-5 lg:grid-cols-2">{rows.map(row => <article key={row.id} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-apple-soft"><div className="flex justify-between gap-4"><div><h2 className="text-lg font-bold text-ink">{row.name}</h2><p className="mt-1 text-sm text-slate-500">{row.subject_name}{row.level ? ` · ${row.level}` : ""}</p></div><div className="flex"><button onClick={() => setEditing(row)} className="rounded-lg p-2 text-slate-400 hover:bg-brand/10 hover:text-brand"><Pencil size={17}/></button><button onClick={() => remove(row.id)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={17}/></button></div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Siswa</p><p className="mt-1 text-lg font-bold text-ink">{row.student_ids.length}/{row.capacity}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Mentor</p><p className="mt-1 text-lg font-bold text-ink">{row.mentor_ids.length}</p></div></div><p className="mt-4 text-sm text-slate-500">{row.package_name ?? "Tanpa paket khusus"}</p></article>)}{rows.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-slate-500 lg:col-span-2">Belum ada kelas. Tambahkan kelas pertama untuk memulai.</div>}</div>
    {editing !== undefined && <div className="fixed inset-0 z-[60] flex items-end bg-slate-900/30 backdrop-blur-sm sm:items-center sm:justify-center sm:p-6"><div className="max-h-[94vh] w-full overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl sm:max-w-3xl sm:rounded-3xl"><div className="mb-6 flex justify-between"><div><h2 className="app-title-secondary">{editing ? "Kelola Kelas" : "Tambah Kelas"}</h2><p className="mt-1 text-sm text-slate-500">Tentukan informasi kelas dan penempatannya.</p></div><button onClick={close} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X/></button></div>{message && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</p>}
      <form onSubmit={event => { event.preventDefault(); submit(event.currentTarget); }} className="grid gap-4 sm:grid-cols-2"><Field label="Nama kelas"><input name="name" required defaultValue={editing?.name ?? ""} className="input"/></Field><Field label="Mata pelajaran"><select name="subject_id" required defaultValue={editing?.subject_id ?? ""} className="input"><option value="">Pilih mata pelajaran</option>{subjects.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Paket (opsional)"><select name="package_id" defaultValue={editing?.package_id ?? ""} className="input"><option value="">Semua paket</option>{packages.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Tingkat (opsional)"><input name="level" defaultValue={editing?.level ?? ""} className="input"/></Field><Field label="Kapasitas"><input name="capacity" type="number" min="1" required defaultValue={editing?.capacity ?? 20} className="input"/></Field><Field label="Deskripsi"><input name="description" defaultValue={editing?.description ?? ""} className="input"/></Field><div className="sm:col-span-2 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100">Batal</button><button disabled={isPending} className="rounded-xl bg-brand px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{isPending ? "Menyimpan..." : "Simpan Kelas"}</button></div></form>
      {editing && <div className="mt-8 grid gap-6 border-t border-slate-100 pt-6 sm:grid-cols-2"><MemberSection title="Siswa di kelas" icon={<Users size={17}/>} options={students} selected={selectedStudentIds} disabled={isPending} onChange={(id, add) => mutateMember("student", editing.id, id, add)}/><MemberSection title="Mentor pengajar" icon={<Users size={17}/>} options={mentors} selected={selectedMentorIds} disabled={isPending} onChange={(id, add) => mutateMember("mentor", editing.id, id, add)}/></div>}</div></div>}
  </>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-sm font-medium text-slate-700">{label}</span>{children}</label>; }
function MemberSection({ title, icon, options, selected, disabled, onChange }: { title: string; icon: React.ReactNode; options: { id: string; full_name: string }[]; selected: Set<string>; disabled: boolean; onChange: (id: string, add: boolean) => void }) { return <section><h3 className="mb-3 flex items-center gap-2 font-semibold text-ink">{icon}{title}</h3><div className="max-h-56 divide-y divide-slate-100 overflow-y-auto rounded-xl border border-slate-200">{options.map(option => { const added = selected.has(option.id); return <div key={option.id} className="flex items-center justify-between gap-2 px-3 py-2.5 text-sm"><span className="truncate text-slate-700">{option.full_name}</span><button disabled={disabled} onClick={() => onChange(option.id, !added)} className={`inline-flex shrink-0 items-center gap-1 rounded-lg px-2 py-1 text-xs font-semibold ${added ? "bg-red-50 text-red-600" : "bg-brand/10 text-brand"}`}>{added ? <><UserMinus size={14}/>Hapus</> : <><UserPlus size={14}/>Tambah</>}</button></div>; })}{options.length === 0 && <p className="p-3 text-sm text-slate-500">Data belum tersedia.</p>}</div></section>; }
